

Game: *.o
	g++ *.o -o Game -LC:\Users\kkaua\OneDrive\Documentos\SFML\SFML-2.5.1\lib -lsfml-graphics -lsfml-window -lsfml-system

Changes: *.cpp *.h
	g++ -c *.cpp -IC:\Users\kkaua\OneDrive\Documentos\SFML\SFML-2.5.1\include

clean:
	rm *.o Game
	aaaaaaaaaaaaaaaaaaaaaa